### ISSUE TITLE
delta classify error summary output - regions of interest

### ISSUE THREAD

**Issue by mvonpohle** [nasa/delta#95]
### Goal: When running DELTA classify, output error metrics for a list of regions of interest. 
- Error Metrics: precision, recall, accuracy, loss, subcomponents of loss
- Regions of Interest: file name of image and polygon(?) for region of interest

### Implementation:
- error metrics/regions of interest provided in a yaml config file. Possibly as part of dataset config?

Name brainstorm:

- targeted error output
- specific error output
- focused
- specific
- area of interest
- polygon error
- subset
- region error
- subregion error
- area of interest error
- region of interest errer

**Comment by mvonpohle** [comment]
It kinda depends on how image metadata is represented internally, but I'm thinking it'd be easiest to annotate regions of interest using QGIS/ArcGIS and then export them as GEOjson or WKT. (This would also let USGS send us regions they'd like to track as well and we could integrate them into the summary report we send them.)

We could either:
- list the raw geojson/wkt text in the config file
    - I'm leaning towards WKT since it has the least unneeded metadata for our purposes. 
- simply reference the corresponding file itself in the config.
    - I think this is the cleanest implementation as files could be loaded/saved directly from QGIS/ArcGIS once the image-file associate has been made in the config 

The example regions of interest include a simple polygon, a polygon with a hole in it, and two non overlapping polygons as a single multi polygon. The polygons overlap image 1037 if you want to load them in QGIS for visualization.

![image](https://user-images.githubusercontent.com/33538453/119745764-a11c3a00-be43-11eb-9f2f-e0e8570d7747.png)

Example config:
```yaml
    regions_of_interest:
      - region:
          file: 1037.tiff
          wkt_file: test_shapefile.csv # either file name or raw text
      # - region: ....
```

[test_shapefile.geojsonl.json.txt](https://github.com/nasa/delta/files/6550254/test_shapefile.geojsonl.json.txt)

Example geojson:
```json
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -94.9994776, 29.7303519 ], [ -94.9955842, 29.7213072 ], [ -94.9894146, 29.7238229 ], [ -94.9760571, 29.723763 ], [ -94.9656346, 29.7410739 ], [ -94.9888156, 29.746345 ], [ -94.9994776, 29.7303519 ] ] ] ] } }
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -95.0028656, 29.727319 ], [ -94.9846864, 29.7558717 ], [ -95.0108768, 29.7695318 ], [ -95.0156014, 29.7695318 ], [ -95.0156014, 29.7594665 ], [ -95.0180663, 29.7578232 ], [ -95.0180663, 29.7566934 ], [ -95.0189907, 29.7502228 ], [ -95.0189907, 29.7459091 ], [ -95.0189907, 29.7360492 ], [ -95.0108768, 29.7357411 ], [ -95.0071794, 29.728038 ], [ -95.0028656, 29.727319 ] ], [ [ -95.010466, 29.7596719 ], [ -94.9990655, 29.7573096 ], [ -94.9983465, 29.7484768 ], [ -95.0107741, 29.7519688 ], [ -95.010466, 29.7596719 ] ] ] ] } }
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -94.9664045, 29.7563853 ], [ -94.9462738, 29.7613152 ], [ -94.9589068, 29.7629585 ], [ -94.9664045, 29.7563853 ] ] ], [ [ [ -94.9633233, 29.7536122 ], [ -94.9658909, 29.7487849 ], [ -94.9607556, 29.7422116 ], [ -94.9398032, 29.7453956 ], [ -94.9462738, 29.7578232 ], [ -94.9633233, 29.7536122 ] ] ] ] } }
```

[test_shapefile.csv](https://github.com/nasa/delta/files/6550255/test_shapefile.csv)

Example WKT:
```WKT
WKT,
"MULTIPOLYGON (((-94.9994776030082 29.7303519404084,-94.988815572031 29.7463449868742,-94.9656346395132 29.741073870436,-94.9760570742886 29.7237630448607,-94.9894145625353 29.7238229439112,-94.99558416473 29.721307183793,-94.9994776030082 29.7303519404084)))"
"MULTIPOLYGON (((-95.0028656393233 29.7273190369212,-95.0071793543717 29.7280379894293,-95.0108768244133 29.7357410520158,-95.0189907170044 29.7360491745193,-95.0189907170044 29.7459090946301,-95.0189907170044 29.7502228096785,-95.018066349494 29.7566933822512,-95.018066349494 29.7578231647639,-95.0156013694664 29.7594664847824,-95.0156013694664 29.7695318198955,-95.0108768244133 29.7695318198955,-94.984686411619 29.755871722242,-95.0028656393233 29.7273190369212),(-95.0104659944086 29.7596718997847,-95.0107741169121 29.7519688371982,-94.9983465092725 29.7484767821589,-94.9990654617806 29.7573096272582,-95.0104659944086 29.7596718997847)))"
"MULTIPOLYGON (((-94.9664044764136 29.7563852597478,-94.9589068288294 29.7629585398216,-94.9462738061874 29.7613152198032,-94.9664044764136 29.7563852597478)),((-94.963323251379 29.7536121572166,-94.9462738061874 29.7578231647639,-94.9398032336147 29.7453955571243,-94.9607555638501 29.7422116245885,-94.9658909389078 29.7487849046624,-94.963323251379 29.7536121572166)))"
```

**Comment by mvonpohle** [comment]
On the output side I'm thinking it'd be useful to associate each image/region polygon pair with a hash of their inputs (image name and region polygon text) so identical regions can be tracked between runs?

**Comment by mvonpohle** [comment]
These are some rough ideas, but let me know what you think @bcoltin @ScottMcMichael

**Comment by bcoltin** [comment]
Sorry Michael, I had half written this up on Monday and then SG kindly rebooted my computer for me :/

Here is my suggestion, add a new section to the config for the classify command. But by default with nothing specified, it would do the current behavior.

classify:
  metrics:
    - Precision
    - Recall
    - ...
  regions:
    - Urban
       - filename.tiff
          bbox: [x1, y1, x2, y2]
       - filename2.tiff # (default to full image with no bbox)
    - Region 2 ....
   results_file: results.txt # optionally save results to file

Metrics let you specify tensorflow metrics to evaluate in the same way as in the train section. Defaults to current behavior. Only evaluates if labels are given.

Regions let you specify a list of named regions to evaluate. The filenames would be specified in the dataset section along with their (optional) labels. If given, could have a flag to output the image results in a folder with the region name as well. Defaults to one region with all images in dataset if not specified.

results_file: Save metrics for regions to a text file. Would be useful to include in uploaded results.

**Comment by bcoltin** [comment]
I like the wkt file, that sounds better than the bounding box if that is easy with arcgis!

The hashing idea sounds good, could be included in the results_file.

**Comment by mvonpohle** [comment]
> Here is my suggestion, add a new section to the config for the classify command. But by default with nothing specified, it would do the current behavior.
> 
> classify:
> metrics:
> - Precision
> - Recall
> - ...
> regions:
> - Urban
> - filename.tiff
> bbox: [x1, y1, x2, y2]
> - filename2.tiff # (default to full image with no bbox)
> - Region 2 ....
> results_file: results.txt # optionally save results to file
> 

I think a new section sounds like a good place for this

> Metrics let you specify tensorflow metrics to evaluate in the same way as in the train section. Defaults to current behavior. Only evaluates if labels are given.

👍

> 
> Regions let you specify a list of named regions to evaluate. The filenames would be specified in the dataset section along with their (optional) labels. If given, could have a flag to output the image results in a folder with the region name as well. Defaults to one region with all images in dataset if not specified.

I like the idea of being able to associate an optional name with a set of regions. And the default just being one unnamed region. Though this could get complicated depending on how specific we want to get with this. (e.g. an urban set that spans multiple images, a river set that spans multiple images, multiple images and associated wkt files in one region). I don't know how much of this complicated example we'd end up needing so maybe starting with the following assumptions: 
- each image gets one wkt_csv file
    - so we don't have to worry about combining files for a single image or files that span multiple images
    - we could also force a convention that the wkt_csv file has the same file name like 1005.wkt.csv
- in the csv there's a tag column where you can list names to associate with each polygon. We can output grouped metrics for all polygons that share a tag.

I'd say output:
- the entire set as a summary regardless of any regions given (and if no regions, this would be all that's output. essentially current behavior)
- each tag as a summary of all polygons that share the tag (images without regions would be assigned a tag of their image name and would be output as a single image-tag summary)
- each unnamed polygon would get a separate summary (internally tag as a hash of the polygon WKT text)
This way tagged polygons, untagged whole images, and untagged polygons can all be tracked from model to model change using their tags.

Example config:
```yaml
regions:
    - image: 1005.tiff
    wkt_csv: 1005.wkt.csv # one column is the WKT for the polygon and the other is a comma separated list of tags
    - image: 1037.tiff # no regions for this tiff, just calculate for entire image. tag will be image name
```
Example wkt.csv file with tags:
```csv
WKT,tag
# this polygon will be tagged urban
"MULTIPOLYGON (((-94.9994776030082 29.7303519404084,-94.988815572031 29.7463449868742,-94.9656346395132 29.741073870436,-94.9760570742886 29.7237630448607,-94.9894145625353 29.7238229439112,-94.99558416473 29.721307183793,-94.9994776030082 29.7303519404084)))",urban 
# this polygon will be tagged urban and river
"MULTIPOLYGON (((-95.0028656393233 29.7273190369212,-95.0071793543717 29.7280379894293,-95.0108768244133 29.7357410520158,-95.0189907170044 29.7360491745193,-95.0189907170044 29.7459090946301,-95.0189907170044 29.7502228096785,-95.018066349494 29.7566933822512,-95.018066349494 29.7578231647639,-95.0156013694664 29.7594664847824,-95.0156013694664 29.7695318198955,-95.0108768244133 29.7695318198955,-94.984686411619 29.755871722242,-95.0028656393233 29.7273190369212),(-95.0104659944086 29.7596718997847,-95.0107741169121 29.7519688371982,-94.9983465092725 29.7484767821589,-94.9990654617806 29.7573096272582,-95.0104659944086 29.7596718997847)))","urban, river" 
# this polygon will be tagged with the hash of its WKT text
"MULTIPOLYGON (((-94.9664044764136 29.7563852597478,-94.9589068288294 29.7629585398216,-94.9462738061874 29.7613152198032,-94.9664044764136 29.7563852597478)),((-94.963323251379 29.7536121572166,-94.9462738061874 29.7578231647639,-94.9398032336147 29.7453955571243,-94.9607555638501 29.7422116245885,-94.9658909389078 29.7487849046624,-94.963323251379 29.7536121572166)))", 
```

> 
> results_file: Save metrics for regions to a text file. Would be useful to include in uploaded results.

👍

> I like the wkt file, that sounds better than the bounding box if that is easy with arcgis!

I'm currently still using QGIS and it's relatively easy to output and edit in QGIS. I _thiiiink_ it should be similarly easy in ArcGIS as well.

**Comment by bcoltin** [comment]
Ok, that makes it easier if the wkt files support tags! I like all your suggestions!

**Comment by ScottMcMichael** [comment]
That sounds good for the region specification.  Is there any documentation of how the desired region metrics are currently calculated in the prediction code?

**Comment by bcoltin** [comment]
Right now it is less generic--- we compute the confusion matrix over the entire region. We should probably still do this, keep the existing option to save as a pdf, and also include the full confusion matrix in the text file output.

**Comment by mvonpohle** [comment]
> Ok, that makes it easier if the wkt files support tags! I like all your suggestions!

For clarity WKT is just a standardized textual form for describing a polygon and the file I listed is a csv with each row being a polygon and the columns being the WKT for the polygon and a tag. We could define any additional columns we wanted for polygons as well. At least in QGIS you can add "fields" which are the other rows when you create a polygon.
